### ISSUE TITLE
Binary Tree Traversals

### ISSUE THREAD

**Issue by GSNCodes** [Py-Contributors/Hacktoberfest-2020#109]
**Title** - 
Binary Tree Traversals

**what will change** - 
A class based tree traversal code will be added in Python.

**Assignees** - 
@ GSNCodes
### Type of Issue 
- [x] Adding New Code

### Programming Language
- [x] Python

**Comment by SuyashGupte** [comment]
Can I work on this task?

**Comment by GSNCodes** [comment]
@SuyashGupte I've created this issue to work on it. Sorry :/
