### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by chemsedd** [Py-Contributors/Hacktoberfest-2020#263]
**Update README.md** - 

**Fixing typos and grammar mistakes on the documentation** - 

### Type of Issue 
Please add/delete options that are not relevant.
- [x] Improving Documentation

**Comment by codePerfectPlus** [comment]
@chemsedd Thanks for creating the issue, Bu this repo is not participating in the HacktpoberFest event. You can find disclaimer in the README. we support the real spirit of Hacktober to support Open-source contributions. 
This repo is only for learning purpose. how to create issues and Pull request in Hacktoberfest for newbies.
Thanks

**Comment by chemsedd** [comment]
I know, i've already read it and i thought it may need some fixing for new comers that's all.
