### ISSUE TITLE
Basic Calculator Update

### ISSUE THREAD

**Issue by Sumanth2905** [Py-Contributors/Hacktoberfest-2020#28]
I want to update the Basic Calculator code 😎

**Comment by Sumanth2905** [comment]
---
about: For creating an issue for HacktoberFest
title: 'Improve code '
labels: Hacktoberfest
assignees: ' @Sumanth2905 '

---

**Title** -  **Improve Basic calculator code**

**What will change** -
handle exception in division part will be added


### Type of Issue 
- [x] Improving Code

### Programming Language
- [x] Python

**Comment by codePerfectPlus** [comment]
- [ ] Assigned

**Comment by codePerfectPlus** [comment]
Make A PR between 1Oct-31Oct for Valid HacktoberFest PR
