### ISSUE TITLE
Improve Basic Calculator

### ISSUE THREAD

**Issue by Ind-Kartikey** [Py-Contributors/Hacktoberfest-2020#29]
assignees: ' @Ind-Kartikey '
**Title** - Improve Basic Calculator

**what will change** - 
I'll update code for basic calculator, will add options to get square root, add or subtract decimal values, get answers of questions with more than 1 operation symbol 

### Type of Issue 
Please add/delete options that are not relevant.
- [x] Improving Code
- [x] Add Functionality

### Programming Language
Please add/delete options that are not relevant.
- [x] Python

**Comment by sb2356-iiitr** [comment]
Hi @Ind-Kartikey , are you going to assign issues to someone or can we start working on them...I am new to open source and wish to participate in Hacktoberfest 2020

**Comment by codePerfectPlus** [comment]
Thanks for considering the issue, but someone already assigned for this already.

suggestion:- Create a new file for the Calculator App, so Your code will not conflict with other's code.

example:-  basicCalculatorPlus.py

**Comment by Ind-Kartikey** [comment]
> Thanks for considering the issue, but someone already assigned for this already.
> 
> suggestion:- Create a new file for the Calculator App, so Your code will not conflict with other's code.
> 
> example:- basicCalculatorPlus.py

Thank you!, So I have to pull it between 1 to 30 Oct?

**Comment by codePerfectPlus** [comment]
For Valid HacktoberFest PR issue, you have to Make PR between 1Oct - 31 Oct.

**Comment by AmeyaJain-25** [comment]
Hello @codePerfectPlus ,
I have more idea to work on with this in improvement of Basic Calculator.
Can I make a PR to this.
I'm new to contributing.
So, let me know that can I make a PR or I cannot.

**Comment by 18-Ritika** [comment]
I want to make some new idea for improving functionality . 
Can I make a PR.
