### ISSUE TITLE
create a hello world program in C++

### ISSUE THREAD

**Issue by codePerfectPlus** [Py-Contributors/Hacktoberfest-2020#3]
- Write your first C++ `Hello World` Program

**Comment by hosseinsharifi3154** [comment]
Hi
can I code this?

**Comment by codePerfectPlus** [comment]
Check Readme.md and register yourself for your Hacktoberfest-2020.
here is the link -  https://hacktoberfest.digitalocean.com/

Open 4 pull-request between 1 oct-31 oct and win free T-shirt.

Official Site- https://hacktoberfest.digitalocean.com/

Thanks,
Py-Contributors team.

[https://hacktoberfest.digitalocean.com/og-hf-teaser.png]<https://hacktoberfest.digitalocean.com/>
Hacktoberfest presented by DigitalOcean | home<https://hacktoberfest.digitalocean.com/>
Companies. Hacktoberfest is a great resource for technology companies looking to increase participation in their open source projects. Your company can participate by encouraging people to contribute to your repositories, organizing community events, or engaging internal employees.
hacktoberfest.digitalocean.com

________________________________
