### ISSUE TITLE
Tower of Hanoi

### ISSUE THREAD

**Issue by tauseefmohammed2** [Py-Contributors/Hacktoberfest-2020#38]
**Title** - Program to Solve Tower of Hanoi Problem

**What will Change** - Addition of New Code

**Assignees** - 

### Type of Issue 
- [x] Improving Code
- [x] Adding New Code

### Programming Language
- [x] Python

**Comment by tauseefmohammed2** [comment]
I would like to contribute the solution for Tower of Hanoi Problem to the Repository as part of Hacktoberfest.

**Comment by codePerfectPlus** [comment]
- [x] assigned @tauseefmohammed2

**Comment by krishshah920** [comment]
I would like to contribute to the tower of hanoi program

**Comment by ViivekUV** [comment]
I'd like to contribute. Please assign it to me
