### ISSUE TITLE
URL shortener

### ISSUE THREAD

**Issue by shubham5351** [Py-Contributors/Hacktoberfest-2020#39]
I would like to work on this issue

**Title** - URL Shortener

**what will change** - 

**Assignees** - 

### Type of Issue 
Please add/delete options that are not relevant.
- [x] Improving Code
- [x] Improving Documentation
- [x] Adding New Code

### Programming Language
Please add/delete options that are not relevant.
- [x] Python

**Comment by tamerharsh** [comment]
Can i work on this ?

**Comment by codePerfectPlus** [comment]
the issue already assigned @tamerharsh
