### ISSUE TITLE
Coronavirus Stats

### ISSUE THREAD

**Issue by iamlordutkarsh** [Py-Contributors/Hacktoberfest-2020#44]
**Title** - Coronavirus Stats

**what will change** - Program to get coronavirus statics in region 

**Assignees** -  @iamlordutkarsh 

### Type of Issue 
- [✓] Improving Code
- [✓] Improving Documentation
- [✓] Adding New Code

### Programming Language
- [x] Python

**Comment by shubham2704** [comment]
hello @iamlordutkarsh , I would like to work on this issue.

**Comment by iamlordutkarsh** [comment]
Sorry @shubham2704 I am Assigned To this And I Completed Work Already Tommorow I will Create Pull Request

**Comment by iamlordutkarsh** [comment]
https://github.com/Py-Contributors/Hacktoberfest-2020/pull/72
