### ISSUE TITLE
finding the sum of all the elements in an array from indices L to R

### ISSUE THREAD

**Issue by heyyviv** [Py-Contributors/Hacktoberfest-2020#53]
Title - finding the sum of all the elements in an array from indices from L to R 

it should have update option to change data store in certain index  
start this command with   1 data index (ex 1 3 4) ( 3 is data 4 is index)

it should return sum of element from index L to R 
start this command with 2  L R (ex 2  3 6) ( 3 is Left index R id right index)

if user type 0 in start of a command then  execution of program is stop.

input 
5 (size of array)
1 2 3 4 5 (array)
1 3 4
2 3 4 
0
output
7

**what will change** - 

Assignees - @heyyviv 

### Type of Issue 
Please add/delete options that are not relevant.
- [✓] Adding New Code

### Programming Language
Please add/delete options that are not relevant.
- [✓] Python

**Comment by sakshi006** [comment]
Can i work on this issue?
