### ISSUE TITLE
Join Py-Contributors

### ISSUE THREAD

**Issue by DrakeEntity** [Py-Contributors/Hacktoberfest-2020#9]
#### Py-contributors is open-source community for

- Python 
- Machine learning 
- Deep learning 
- Data Science  

If you are interested in any of these then you are welcome to the community. Share you Github username below for invitation.

- Discord  - https://discord.gg/p8PCpb
- Telegram - https://t.me/pycontributors

**Comment by sameer-j** [comment]
I would like to be a part.
Username : sameer-j

**Comment by brtymn** [comment]
I would like to be a part.
Username: brtymn

**Comment by codePerfectPlus** [comment]
Thanks for showing interest.
You will receive email for joining. 

@sameer-j  @brtymn 

Happy Coding

**Comment by crnguyen** [comment]
I'd like to contribute.
username: crnguyen
